### ISSUE TITLE
Feature request: iOS Version Check?

### ISSUE THREAD

**Issue by hemangshah** [dennisweissmann/DeviceKit#119]
It would be nice to see if DeviceKit can check for the iOS version and handling it very easily.

Any thoughts?

**Comment by dennisweissmann** [comment]
Hm, not sure this is the right place for this because Device is more hardware-related. What did you imagine? Something along 

https://developer.apple.com/documentation/foundation/processinfo/1408730-operatingsystemversionstring

and https://developer.apple.com/documentation/foundation/processinfo/1414876-isoperatingsystematleast
?

**Comment by dennisweissmann** [comment]
Closed due to inactivity
