### ISSUE TITLE
watchOS Support

### ISSUE THREAD

**Issue by chadmoone** [dennisweissmann/DeviceKit#135]
Is there any particular reason why watchOS is not currently supported?

**Comment by chadmoone** [comment]
Well, I was asking this to get a read before investing time into putting together a PR, but I ended up just starting on it anyway, and now I've got it mostly done.

One thing I'm a little unsure of is `.gyb` file, which looks like it's used to actually generate the swift file.  Right now I've got all my changes in the swift directly, and can try porting them out into the gyb, but 
1. I wanted to make sure that's still how you are maintaining this project, and 
2. I was curious if there are any docs for this workflow (I didn't see any in the repo).

I'm also curious whether you view it as a significant timesaver. Looking at the line lengths, there doesn't seem to be that much less code in the `gyb`, and there are now two files to maintain, so I was just wondering if you still find it to be impactful.

Thanks!

**Comment by serjooo** [comment]
Hello! I currently require DeviceKit to support watchOS as well. Wondering if I can help in any way. I am also unsure how to effectively use the ‘gyb’ but I’m always willing to learn to be able to contribute to this amazing project!

**Comment by dennisweissmann** [comment]
Hi @serjooo,

That's great!

Basically, at the top of the gyb file is a large python array of all the devices we support (or one array for each "device group", i.e. iPhone, iPad, HomePod, Apple TV, etc., watch would be another one of those categories).

In these arrays we maintain all the data we support, and later, in the swifty part of the file we reference those tables.

It's basically a very powerful pre-processor.
Every line that starts with a `%` is python code (mostly for loops) that iterate over the stuff inside of them, e.g.

```
% for device in iOSDevices:
    /// ${device.comment}
    ///
    /// ![Image](${device.imageURL})
    case ${device.caseName}
% end
```

loops over all iOSDevices (which is one of those variables defined at the top) and generates for each of the array elements the code between the python-line-indicating `%` symbols. This means we don't have to list all of the devices manually (and forget images, etc.) but can conveniently use the information we collected in one central place (you guessed it: at the top :)).

Inside lines that do not start with `%` you can still use values of the variables you defined, this is what happens in lines 2 and 4. with `${variable}` - we get the value of the `comment` field on the `device` variable (which, in this case, is our local loop variable) and gyb automatically inserts the value of that field as text in that position.

Let's assume our `iOSDevices` array contains [Devices](https://github.com/dennisweissmann/DeviceKit/blob/master/Source/Device.swift.gyb#L13-L25) for iPad 2 and iPad 3. This is what would get generated:

   

>     /// Device is an [iPad 2](https://support.apple.com/kb/SP622)
>     ///
>     /// ![Image](https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP622/SP622_01-ipad2-mul.png)
>     case iPad2
>     /// Device is an [iPad (3rd generation)](https://support.apple.com/kb/SP647)
>     ///
>     /// ![Image](https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP662/sp662_ipad-4th-gen_color.jpg)
>     case iPad3

It's important to note that gyb does *not at all* care what it generates :) It's not restricted to Swift code or anything programming related - you can use it everywhere you want it to (g)enerate (y)our (b)oilerplate :)

This is just a very brief overview, I hope that helps a bit, if you need more help do not hesitate, I love that you all use the project and even want to contribute back, so I'm here to help! :)

Thank you!

**Comment by robbiet480** [comment]
Okay, so now i'm picking this up because I need DeviceKit in Home Assistant for watchOS :)

Here's the first issue, hopefully the last. How do we handle all the different combinations of features? Apple seems to have unique pages for each style (Apple Watch 1st generation Sport, Apple Watch 1st generation Stainless, Hermes, etc etc). The 38mm is identified as WatchX,1 and the 42mm is identified as WatchX,2 (where X is the generation number).

I can add individual devices for every combination but that seems like a bit much. I can combine some combinations together (such as representing Sport, Nike, Stainless as one) but split by size and for Series 3+, WiFi or LTE.

Actually, writing this out has made me choose to do the latter. So the devices i'm adding will look like this (formatted for easier reading on GitHub):

```swift
Device(
"appleWatchSeries0_38mm",
"Device is an [Apple Watch (1st generation)](https://support.apple.com/kb/sp736)",
"https://support.apple.com/library/content/dam/edam/applecare/images/en_US/applewatch/watch-38mm-silver-alum.png",
["Watch1,1"], 1.5, (4,5), "Apple Watch (1st generation) 38mm", 303, False, False, False, False, False, False)
```

Is that acceptable? So one device per screen size and connectivity type.

Let me know @dennisweissmann!

**Comment by dennisweissmann** [comment]
Hi Robbie, thanks for tackling this! Awesome! That said I don’t like 0_38 too much :( it doesn’t look very nice, what would you think about .appleWatch(series: Int, size: Int). WiFi and LTE could be a property (which we could also support for iPods/iPads. Since you need it, would you code at the call site be nice and easy to understand that way? Or should we stay consistent with the iPhones and put the series in the name (now that I think about it that’s probably better, so `appleWatchSeriesX(size: Int)`. What do you think? Is that workable at the call-site or would you prefer completely different cases for each size?

**Comment by robbiet480** [comment]
I understand the annoyance about `0_38`. The reason I chose that is because Apple seems to think of the 38/40mm and 42/44mm devices as standalone from one another, as evidenced by WatchX,1 and WatchX,2 and different support spec pages.

I think it would be good to keep Series in the name. We have iPhone 3, 4, 5, why not Watch 1, 2, 3. Apple calls the very first released Watch "Apple Watch (1st generation)" but many people outside of Apple call it Series 0. Is Series 0 acceptable?

**Comment by robbiet480** [comment]
@dennisweissmann I've pushed my initial work that still uses _38mm, _42mm, etc. I'm somewhat unsure of how to implement your suggested method, I thought I got it at the time but I guess not. If you could provide a bit of a larger example on how to implement it, I can get it done! In the meantime, there's a PR for everyone to poke at 😄

**Comment by robbiet480** [comment]
@dennisweissmann Another note, I set minimum SDK to 4.0 for watchOS. We could probably go lower, maybe even to 1, but wasn't sure what your policy is...

**Comment by dennisweissmann** [comment]
Sorry for the delay, if we could go lower that would be great, we can go with `@available` annotations for functions which are not available in older SDKs, does that make sense?

**Comment by robbiet480** [comment]
@dennisweissmann Yep! I'll get that taken care of within the next 24 hours

**Comment by dennisweissmann** [comment]
Thank you :) Take whatever time you need, I really appreciate your contribution!

**Comment by robbiet480** [comment]
@dennisweissmann Just pushed a commit to allow use on watchOS 2.0 by only exposing battery state on 4.0 and above.

There's still my outstanding comment [here](https://github.com/dennisweissmann/DeviceKit/issues/135#issuecomment-428030341) that I could use your help on.

**Comment by dennisweissmann** [comment]
That’s great, sorry for the delays ... I’ll get to a computer and take a look, regarding the function you thought you got but didn’t: I’m not sure what you mean :D which function are we talking about? 🙈

**Comment by robbiet480** [comment]
I was talking about your suggestion of instead of doing _38 and _42 instead something like `appleWatchSeriesX(size: Int)`. I'm unsure how to implement that in the gyb.

**Comment by robbiet480** [comment]
Woohoo!!! 🎉
