### ISSUE TITLE
Unable to build with Swift 4 and XCode 10 beta 3.  

### ISSUE THREAD

**Issue by tethridge** [dennisweissmann/DeviceKit#138]
Should be a simple change.  The isGuidedAccessSessionActive parameter needs to be updated.  

/Users/tethridge/Projects/iOS/Anywhere/Pods/DeviceKit/Source/Device.generated.swift:568:12: 'UIAccessibilityIsGuidedAccessEnabled()' has been replaced by property 'UIAccessibility.isGuidedAccessEnabled'

/UIKit.UIAccessibilityIsGuidedAccessEnabled:3:13: 'UIAccessibilityIsGuidedAccessEnabled()' was obsoleted in Swift 3

**Comment by dennisweissmann** [comment]
Hi, sorry for the delay, which version are you using?

**Comment by dennisweissmann** [comment]
I'm currently working on the fixes needed for Xcode 10.

I was reluctant to add them because travis does not yet have support for Xcode 10, however, I see that there is a need for this and I will push it later so that everyone who is on master (or does not specify a version in CocoaPods) can continue to use it.

In general: master is the dev branch and you should (in general) not use it as it might change frequently and might be unstable.

Once there is support for Xcode 10 on travis I'll create a swift42 branch which is then used for the next release (in fall this year) :)

Hope that works for everyone, if not please let me know!

**Comment by dennisweissmann** [comment]
Fixed by 661c321144657fda10bdc7cf338f8aa361f86141 :)
