### ISSUE TITLE
Xcode 7.3 - swift switch must be exhaustive consider adding a default clause

### ISSUE THREAD

**Issue by phiren** [dennisweissmann/DeviceKit#19]
The project working well on xcode 7.2 have issue in xcode 7.3
![screen shot 2016-03-25 at 1 09 21 pm](https://cloud.githubusercontent.com/assets/8377260/14040218/d3616f24-f28a-11e5-9a59-6d5539504f0f.png)

**Comment by phiren** [comment]
Resolved by writing line
            default:            self = .Unspecified

**Comment by dennisweissmann** [comment]
Nice! Do you have by any chance Xcode 7.2 still around and could test it there (when linking against iOS 9.2, because there were problems in #16 with CI. I'm unfortunately not home and cannot work on this right now, if you can please create a pull request that passes CI - I would greatly appreciate that!

**Comment by phiren** [comment]
Yes, its also working on Xcode 7.2. Would you like me to push this changes to this repository?

**Comment by dennisweissmann** [comment]
That would be awesome! :)

**Comment by phiren** [comment]
Hi added pull request, never used it before, please review and confirm.

**Comment by phiren** [comment]
Closing this issue as it resolved :)
