### ISSUE TITLE
Get Device IP Address.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [dennisweissmann/DeviceKit#65]
I want to fetch IP address, when it is connected to network.

**Comment by dennisweissmann** [comment]
Hm, im not sure if this is a good fit for this framework. I thought of Device providing hardware related information, and while getting the current IP address might be a valid use case it's not really HW related. I'll leave this issue open for a while to let others comment and vote, but I think this is a "won't fix". Sorry to disappoint you :( or maybe you can convince me otherwise :)

**Comment by Rashesh-Bosamiya** [comment]
No worries pal.
You're precise by your comment.

Can you help me for this issue by using other resource?

**Comment by dennisweissmann** [comment]
Sure, see http://stackoverflow.com/a/27709110/1489885 but not Rob's comment:

> If by "public IP" you mean "IP address that the Internet will see me as coming from" then that is not possible to know without asking some part of the Internet. NAT does not occur on your device; it occurs on the network. Note that different devices may see you as having a different IP depending on how you route to them (including the possibility that some may see you as having an IPv4 address and other see you with an IPv6 address). "The Internet" is just one particular network; you can be on and route between many different networks w/ different IP mappings.

**Comment by Rashesh-Bosamiya** [comment]
Thanks ★★
